;; THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
;; EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
;; MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
;; NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
;; LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
;; OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
;; WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.


(defpackage :heavy-bool
  (:use :cl)
  (:export
   "heavy-bool"
   "heavy-true"
   "heavy-false"
   "+forall"
   "+exists"
   "+and"
   "+OR"
   "+IMPLIES"
   "+IMPLIED-BY"
   "+IF"
   "+TO-BOOL"
   "+CONJ"
   "+CONJ-TRUE"
   "+CONJ-FALSE"
   "+ANNOTATE"
))
